# Generated by Django 6.0.6 on 2026-06-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.CharField(default='General', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento'), ('daniado', 'Dañado')], default='disponible', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos_img/')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.tipoequipo')),
            ],
        ),
    ]
