# Generated by Django 6.0.4 on 2026-06-03 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrar_departamento_existente(apps, schema_editor):
    TipoEquipo = apps.get_model('inventario', 'TipoEquipo')
    TipoEquipo.objects.filter(departamento='General').update(departamento='GENERAL')


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrar_departamento_existente, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_img/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventario.tipoequipo'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='departamento',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SISTEMAS', 'Sistemas'), ('CONTABILIDAD', 'Contabilidad'), ('LOGISTICA', 'Logística'), ('OPERACIONES', 'Operaciones')], default='GENERAL', max_length=50),
        ),
    ]
