# Generated by Django 6.0.4 on 2026-06-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_equipo_imagen_alter_equipo_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='tipoequipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Equipo', 'verbose_name_plural': 'Tipos de Equipos'},
        ),
    ]
