# Generated by Django 6.0.4 on 2026-06-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_equipo_options_alter_tipoequipo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipo',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='tipos_icono/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_img/'),
        ),
    ]
