# Generated by Django 6.0.6 on 2026-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_tipoequipo_icono_alter_equipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoequipo',
            name='departamento',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SISTEMAS', 'Sistemas'), ('CONTABILIDAD', 'Contabilidad'), ('LOGISTICA', 'Logística'), ('OPERACIONES', 'Operaciones'), ('BIOMEDICA', 'Biomédica'), ('INVESTIGACION', 'Investigación'), ('REDES', 'Redes'), ('MANTENIMIENTO', 'Mantenimiento')], default='GENERAL', max_length=50),
        ),
    ]
